apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: asm-gcp-multiproject
  meshConfig:
    trustDomainAliases: # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.trustDomainAliases"}
    - "banded-lexicon-360413.svc.id.goog"
    - "banded-lexicon-360413.hub.id.goog"
  values:
    global:
      meshID: "proj-334782020989" # {"$ref":"#/definitions/io.k8s.cli.substitutions.mesh-id"}
